# Generated by Django 4.2.2 on 2023-06-29 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaidRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('max_players', models.SmallIntegerField()),
                ('max_bots', models.SmallIntegerField()),
                ('max_cycles', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RaidSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bots', models.JSONField(default=dict)),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Finished')], default=0)),
                ('action_log', models.JSONField(default=list)),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raids.raidrules')),
            ],
        ),
    ]
