# Generated by Django 4.2.11 on 2024-05-01 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bots_result', models.JSONField(blank=True, default=dict, verbose_name='bots result')),
                ('users_result', models.JSONField(blank=True, default=dict, verbose_name='users result')),
                ('action_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bots_killed_value', models.IntegerField(default=0)),
                ('bots_killed_list', models.JSONField(blank=True, default=list)),
                ('robots_killed_value', models.IntegerField(default=0)),
                ('robots_killed_list', models.JSONField(blank=True, default=list)),
                ('experience', models.IntegerField(default=0)),
                ('is_died', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_robots', to='raids.raid')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_robots', to='robots.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_robots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
