# Generated by Django 4.2.2 on 2023-06-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidsession',
            name='action_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='raidsession',
            name='bots',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
