# Generated by Django 4.2.11 on 2024-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
        ('raids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='robots',
            field=models.ManyToManyField(through='raids.UserRaid', to='robots.robot'),
        ),
    ]
