# Generated by Django 4.2.2 on 2023-07-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0003_raidsession_created_at_raidsession_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidsession',
            name='users',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
