# Generated by Django 4.2.2 on 2023-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0004_raidsession_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.JSONField(default=dict)),
                ('bots', models.JSONField(blank=True, default=dict)),
                ('users', models.JSONField(blank=True, default=dict)),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Finished')], default=0)),
                ('action_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='raidsession',
            name='rules',
        ),
        migrations.DeleteModel(
            name='RaidRules',
        ),
    ]
