# Generated by Django 4.2.11 on 2024-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0004_raid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Finished', 'Finished')], default='New', max_length=50, verbose_name='status'),
        ),
    ]
