# Generated by Django 4.2.11 on 2024-05-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0005_alter_raid_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='action_log',
        ),
        migrations.AddField(
            model_name='raid',
            name='log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
