# Generated by Django 4.2.2 on 2023-07-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_userperson_raid_session'),
        ('raids', '0005_userraid_remove_raidsession_rules_delete_raidrules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaidSession',
        ),
    ]
