# Generated by Django 4.2.11 on 2024-05-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_remove_robot_heal_remove_robot_max_damage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='agility',
            new_name='dexterity',
        ),
        migrations.AddField(
            model_name='robot',
            name='charisma',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='robot',
            name='constitution',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='robot',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='robot',
            name='intelligence',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='robot',
            name='wisdom',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='robot',
            name='status',
            field=models.CharField(choices=[('DEAD', 'Нет сигнала'), ('WAITING', 'В режиме ожидании'), ('PREPARATION', 'Подготовка к заданию'), ('ON_MISSION', 'Исполняет задание')], default='WAITING', max_length=64),
        ),
        migrations.AlterField(
            model_name='robot',
            name='strength',
            field=models.SmallIntegerField(default=10),
        ),
    ]
