# Generated by Django 4.2.11 on 2024-05-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_rename_agility_robot_dexterity_robot_charisma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='killed_by',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
