# Generated by Django 4.2.11 on 2024-05-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_robot_killed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='epitaph',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='killed_by',
        ),
    ]
