# Generated by Django 4.2.2 on 2023-07-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperson',
            name='stamina',
        ),
    ]
