# Generated by Django 4.2.2 on 2023-07-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_userperson_stamina'),
        ('raids', '0005_userraid_remove_raidsession_rules_delete_raidrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperson',
            name='raid_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='raids.userraid'),
        ),
    ]
