# Generated by Django 4.2.2 on 2023-07-13 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0006_delete_raidsession'),
        ('persons', '0003_alter_userperson_raid_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonRaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.userperson')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raids.userraid')),
            ],
        ),
    ]
