# Generated by Django 4.2.2 on 2023-07-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfactory',
            name='active_user_person_limit',
            field=models.SmallIntegerField(default=1),
        ),
    ]
